version: 0.0.1.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: Zombie.sln
  verbosity: minimal
install:
  - ps: Install-Product node 5
  - npm install
