version: 0.0.4.{build}
assembly_info:
  patch: true
  file: '**\\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
  - ps: Install-Product node 5
  - npm install
  # Install zombie's modules nested in a single folder for redistribution
  - cd node_modules\zombie
  - npm install --production
  - cd ..\..
before_build:
  - nuget restore
build:
  project: Zombie.sln
  publish_nuget: true
  verbosity: minimal
after_build:
  - nuget pack Zombie.js\zombie.js.nuspec -version 4.2.1.%APPVEYOR_BUILD_NUMBER%
  - appveyor PushArtifact ./zombie.js.4.2.1.%APPVEYOR_BUILD_NUMBER%.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: tqiGBmod5X4QAhyd+yCL/+RqAOVouFERgnOQU8Ln2ayL+0C6usRgACow6EsUN7Gw
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true
