version: 0.0.6.{build}
assembly_info:
  patch: true
  file: '**\\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
  - ps: Install-Product node 5
  - npm install
before_build:
  - nuget restore
build:
  project: Zombie.sln
  publish_nuget: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: tqiGBmod5X4QAhyd+yCL/+RqAOVouFERgnOQU8Ln2ayL+0C6usRgACow6EsUN7Gw
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true
