version: 0.0.1.{build}
assembly_info:
  patch: true
  file: '**\\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: minimal
environment:
  nodejs_version: "5"
install:
  - npm install
